const CREATE_TASK = "CREATE_TASK";
const UPDATE_TASK_TITLE = "UPDATE_TASK_TITLE";
const ARCHIVE_TASK = "ARCHIVE_TASK";
const UNARCHIVE_TASK = "UNARCHIVE_TASK";
const COMPLETE_TASK = "COMPLETE_TASK";
const INCOMPLETE_TASK = "INCOMPLETE_TASK";

export default {
  CREATE_TASK,
  UPDATE_TASK_TITLE,
  COMPLETE_TASK,
  INCOMPLETE_TASK,
  ARCHIVE_TASK,
  UNARCHIVE_TASK,
};
