const OPEN_DRAWER = "OPEN_DRAWER";
const CLOSE_DRAWER = "CLOSE_DRAWER";
const SHRINK_DRAWER = "SHRINK_DRAWER";
const EXPAND_DRAWER = "EXPAND_DRAWER";

export default {
  OPEN_DRAWER,
  CLOSE_DRAWER,
  SHRINK_DRAWER,
  EXPAND_DRAWER,
};
